apiVersion: v1
kind: Service
metadata:
  name: haproxy
  labels:
    app: haproxy
    tier: backend
    role: standalone
spec:
  ports:
    # the port that this service should serve on
  - port: 14265
    protocol: TCP
    targetPort: 14265
  selector:
    app: haproxy
    tier: backend
    role: standalone
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: haproxy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: haproxy
      name: haproxy
    spec:
      containers:
      - image: haproxy:alpine
        imagePullPolicy: Always
        name: haproxy
        ports:
          - containerPort: 14265
            name: iotaport
            protocol: TCP
        volumeMounts:
          - name: config
            mountPath: /usr/local/etc/haproxy
            readOnly: true
      volumes:
          name: config
					secret:
						secretName: configs
						items:
							key: haproxy
							path: haproxy.cfg



